package livelihoodzone.repository.questionnaire.livelihoodzones;

import livelihoodzone.entity.questionnaire.livelihoodzones.SubLocationsLivelihoodZoneAssignmentEntity;
import org.springframework.data.jpa.repository.JpaRepository;

public interface SubLocationsLivelihoodZoneAssignmentRepository extends JpaRepository<SubLocationsLivelihoodZoneAssignmentEntity, Long> {
}
