package livelihoodzone.repository.questionnaire.county.seasonal_calendar;

import livelihoodzone.entity.questionnaire.county.seasonal_calendar.LzLandPreparationMonthsEntity;
import livelihoodzone.entity.questionnaire.county.seasonal_calendar.LzNonAgricCasualLabourAvailabilityEntity;
import org.springframework.data.jpa.repository.JpaRepository;

public interface LzNonAgricCasualLabourAvailabilityRepository extends JpaRepository<LzNonAgricCasualLabourAvailabilityEntity, Long> {
}
